// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBFprd7kT6ZYKTjj2fcV9VN9cqPDHSSqAY',
    appId: '1:891052842663:web:74c8c43fe6edfae3e14582',
    messagingSenderId: '891052842663',
    projectId: 'kimioto-now',
    authDomain: 'kimioto-now.firebaseapp.com',
    storageBucket: 'kimioto-now.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBFprd7kT6ZYKTjj2fcV9VN9cqPDHSSqAY',
    appId: '1:891052842663:android:74c8c43fe6edfae3e14582',
    messagingSenderId: '891052842663',
    projectId: 'kimioto-now',
    storageBucket: 'kimioto-now.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBFprd7kT6ZYKTjj2fcV9VN9cqPDHSSqAY',
    appId: '1:891052842663:ios:74c8c43fe6edfae3e14582',
    messagingSenderId: '891052842663',
    projectId: 'kimioto-now',
    storageBucket: 'kimioto-now.firebasestorage.app',
    iosClientId: '891052842663-q05keuofsl19qjgi6vlul2k3gqbk925a.apps.googleusercontent.com',
    iosBundleId: 'com.localbeat.events',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBFprd7kT6ZYKTjj2fcV9VN9cqPDHSSqAY',
    appId: '1:891052842663:ios:74c8c43fe6edfae3e14582',
    messagingSenderId: '891052842663',
    projectId: 'kimioto-now',
    storageBucket: 'kimioto-now.firebasestorage.app',
    iosClientId: '891052842663-q05keuofsl19qjgi6vlul2k3gqbk925a.apps.googleusercontent.com',
    iosBundleId: 'com.localbeat.events',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBFprd7kT6ZYKTjj2fcV9VN9cqPDHSSqAY',
    appId: '1:891052842663:web:74c8c43fe6edfae3e14582',
    messagingSenderId: '891052842663',
    projectId: 'kimioto-now',
    authDomain: 'kimioto-now.firebaseapp.com',
    storageBucket: 'kimioto-now.firebasestorage.app',
  );
}
